apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: wpdemo
    kind: SecretStore
  target:
    name: db-wp-demo
    creationPolicy: Owner
  data:
    - secretKey: WORDPRESS_DB_USER
      remoteRef:
        # helm would be able to derive this path in a custom helm chart
        key: /prod/wpdemo/db/wp-demo-creds
        property: user
    - secretKey: WORDPRESS_DB_PASSWORD
      remoteRef:
        key: /prod/wpdemo/db/wp-demo-creds
        property: password
    - secretKey: WORDPRESS_DB_HOST
      remoteRef:
        key: /prod/wpdemo/db/wp-demo-creds
        property: host
    - secretKey: WORDPRESS_DB_NAME
      remoteRef:
        key: /prod/wpdemo/db/wp-demo-creds
        property: dbname
