apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: wpdemo
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-2
      auth:
        secretRef:
          # for now just using access keys that I setup as a secret manually
          # in real prod, this would be a role + IRSA that allows only access to the keys that are needed
          accessKeyIDSecretRef:
            name: iam-user
            key: access-key
          secretAccessKeySecretRef:
            name: iam-user
            key: secret-access-key