# this is a quick demo, in prod we'd use an appset with a template so apps are autodiscovered
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-demo
spec:
  destination:
    namespace: wordpress-demo
    server: https://kubernetes.default.svc
  source:
    path: k8s/apps/wordpress-demo/envs/prod
    repoURL: git@github.com:andrewthetechie/limble-demo.git
    targetRevision: HEAD
  sources: []
  project: apps
