---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  source:
    path: k8s/infra/misc/envs/prod
    repoURL: git@github.com:andrewthetechie/limble-demo.git
    targetRevision: HEAD
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
