---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  destination:
    namespace: eso
    server: "https://kubernetes.default.svc"
  source:
    path: k8s/infra/external-secrets
    repoURL: git@github.com:andrewthetechie/limble-demo.git
    targetRevision: HEAD
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
