apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
metadata:
  name: argocd

resources:
  - namespace.yaml
  - ingress.yaml
  - project-apps.yaml
  - project-infra.yaml
  - infra-argocd.yaml
  - infra-ingress.yaml
  - infra-external-secrets.yaml
  - app-wordpress-demo.yaml
patches:
  - path: configmap.yaml

helmCharts:
  - includeCRDs: true
    name: argo-cd
    namespace: argocd
    releaseName: argocd
    repo: https://argoproj.github.io/argo-helm
    valuesInline:
      server:
        extraArgs:
          - --insecure
        rbacConfig:
          policy.default: role:admin
    version: 7.6.2
