apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
metadata:
  name: aws-load-balancer-controller

helmCharts:
  - name: aws-load-balancer-controller
    releaseName: aws-load-balancer-controller
    namespace: kube-system
    version: 1.8.3
    repo: https://aws.github.io/eks-charts
    includeCRDs: true
    valuesInline:
      # this would be pulled from tf state or another data source and not
      clusterName: prod-cluster
