apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress-demo

resources:
  - ../../base

helmCharts:
  - name: app-template
    releaseName: wordpress-demo
    namespace: wordpress-demo
    version: 3.3.2
    repo: https://bjw-s.github.io/helm-charts
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-dev.yaml
  - name: app-template
    releaseName: wordpress-demo-db
    namespace: wordpress-demo
    version: 3.3.2
    repo: https://bjw-s.github.io/helm-charts
    valuesFile: values-db.yaml
