apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eso

resources:
  - namespace.yaml

helmCharts:
  - name: external-secrets
    namespace: eso
    version: 0.10.0
    repo: https://charts.external-secrets.io
    includeCRDs: true
